### ISSUE TITLE
Question about streaming video & audio from HoloLens

### ISSUE THREAD

**Issue by mirzasohailbaig** [ShanguUncle/UnityChatSDK#1]
Hello, 
I found your streaming implementation intriguing, but my one issue is that it seems you are using a standalone server application that must be running on the PC for chat communication between devices is this really the case ?

If so is there any way you can simply do it without having any middle-ware that acts like server, possibly something where one of the devices that is communicating is the server so you don't need another app to act as the server between the devices ? 

I'm really interested in HoloLens video/audio streaming to different platforms so even if this project costs money I should be able to convince my employer to purchase it so long as it meets our needs.

Best regards,
Sohail Baig

**Comment by ShanguUncle** [comment]
Hi Baig,
This project provides a sdk of audio and video capture and codec.The demo shows that you can compile and run on each platform well, you can use your own network sdk or third-party sdk to build your server. 
Best regards,
Gu

**Comment by mirzasohailbaig** [comment]
How much are you charging for license or is it open source ?

**Comment by ShanguUncle** [comment]
one license can be used permanently, continuously updated.
https://item.taobao.com/item.htm?id=574700900943
