### ISSUE TITLE
hi, I am willing to purchase UnityChatSDK

### ISSUE THREAD

**Issue by CaramelYo** [ShanguUncle/UnityChatSDK#11]
Dear ShanguUncle,

I'm CaramelYo.
I'm interested in your project, and willing to purchase it.
However, I want to know more details about this project.
Might I get your email address for more details by email ?
My email address is alltime326@gmail.com

I look forward to your reply.

Sincerely,
CaramelYo

**Comment by ShanguUncle** [comment]
support email shangu.gu@qq.com.
