### ISSUE TITLE
How to tackle this problem：AssetDatabase' does not contain a definition for 'AllowAutoRefresh'

### ISSUE THREAD

**Issue by USTBVEO** [ShanguUncle/UnityChatSDK#15]
Library\PackageCache\com.unity.collab-proxy@1.14.12\Editor\PlasticSCM\CloudProjectDownloader\DownloadRepositoryOperation.cs(65,31): error CS0117: 'AssetDatabase' does not contain a definition for 'AllowAutoRefresh'

I use unity 2019.3.3

**Comment by ShanguUncle** [comment]
Try to delete the Packages folder.

**Comment by USTBVEO** [comment]
您发给我的信件已收到。from Wei Yang/杨威
 
   This is an automatic reply, confirming that your e-mail was received.Thank you
