### ISSUE TITLE
Trial time is up

### ISSUE THREAD

**Issue by FluffySpectre** [ShanguUncle/UnityChatSDK#2]
Hi,

I get this message after a minute of use:

Trial time is up! Please regester!

Can you tell me, where I get a license?

Thanks in advance!

**Comment by FluffySpectre** [comment]
Got the answer in the other closed issue #1

**Comment by ShanguUncle** [comment]
The professional version costs 1800 RMB, send your registration code after payment.
https://item.taobao.com/item.htm?id=574700900943
https://www.paypal.me/ShanGuUncle

**Comment by FluffySpectre** [comment]
Thank you for the info! Unfortunately I can't register at TaoBao for some reason. I'm not receiving the required verification code to complete the registration (I'm in Germany). 
Is there another way of getting a license?

Thanks in advance for your help!

**Comment by ShanguUncle** [comment]
I will upload it to the assetstore later, you send the order number to the email and get the license.

**Comment by FluffySpectre** [comment]
Thank you very much!

**Comment by FluffySpectre** [comment]
Sorry to bother you again, but is there any chance to get a license until the end of this week?
I develop a maintenance support app at the moment and next week is a demo day, where i need a working video chat.
Thanks in advance!

**Comment by ShanguUncle** [comment]
I have uploaded the sdk to asset store yesterday, it is under review，this week should be OK.


------------------ 原始邮件 ------------------
发件人: "BjoernBo"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 中午1:00
收件人: "ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com>;
抄送: "Gushijie"<1786570525@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ShanguUncle/UnityChatSDK] Trial time is up (#2)




Sorry to bother you again, but is there any chance to get a license until the end of this week?
 I develop a maintenance support app at the moment and next week is a demo day, where i need a working video chat.
 Thanks in advance!

**Comment by ShanguUncle** [comment]
This link will be valid after the platform is approved.
https://assetstore.unity.com/packages/slug/153662
------------------ 原始邮件 ------------------
发件人: "BjoernBo"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 中午1:00
收件人: "ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com>;
抄送: "Gushijie"<1786570525@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ShanguUncle/UnityChatSDK] Trial time is up (#2)




Sorry to bother you again, but is there any chance to get a license until the end of this week?
 I develop a maintenance support app at the moment and next week is a demo day, where i need a working video chat.
 Thanks in advance!

**Comment by ShanguUncle** [comment]
If this has not passed the day after tomorrow, please send me your registration code, I will send you the license, you can buy it later.




------------------ 原始邮件 ------------------
发件人: "BjoernBo"<notifications@github.com>; 
发送时间: 2019年9月9日(星期一) 中午1:00
收件人: "ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com>; 
抄送: "Gushijie"<1786570525@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ShanguUncle/UnityChatSDK] Trial time is up (#2)




Sorry to bother you again, but is there any chance to get a license until the end of this week?
 I develop a maintenance support app at the moment and next week is a demo day, where i need a working video chat.
 Thanks in advance!

**Comment by FluffySpectre** [comment]
Thank you for the fast response and the kind offer! I will start implementing your chat right now.

**Comment by FluffySpectre** [comment]
Hi, 
since the package is not available in the AssetStore in the moment, i would like to send you my application key. I will pay as soon it got online in the AssetStore.
Have you a specific email where I can send it to?

Thanks in advance!

**Comment by ShanguUncle** [comment]
Yes, I have just checked it, just on this email.




------------------ 原始邮件 ------------------
发件人: "BjoernBo"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 中午1:51
收件人: "ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com>; 
抄送: "Gushijie"<1786570525@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ShanguUncle/UnityChatSDK] Trial time is up (#2)




Hi,
 since the package is not available in the AssetStore in the moment, i would like to send you my application key. I will pay as soon it got online in the AssetStore.
 Have you a specific email where I can send it to?
 
Thanks in advance!

**Comment by FreshD91** [comment]
Here is my Application Key: 28hp8DZf3hNweuoL6/jtOg==

**Comment by ShanguUncle** [comment]
C28D26968767EDB7BEE5BDD291E54B6ACC701C06ABA6E7C4EA368CE650C9FEAE|Gv9ys/eEZUoFeefDl0iHbg==
You can register  another computer when you need it.
Please email me if you have any questions.








------------------ 原始邮件 ------------------
发件人: "BjoernBo"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 下午2:11
收件人: "ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com>; 
抄送: "Gushijie"<1786570525@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ShanguUncle/UnityChatSDK] Trial time is up (#2)




Here is my Application Key: 28hp8DZf3hNweuoL6/jtOg==

**Comment by FluffySpectre** [comment]
Thank you very much! Do i need additional keys per development computer or per computer the compiled app is running on?

**Comment by ShanguUncle** [comment]
The licence is used for development. The compiled has no restrictions. A license is only applicable to one computer. One user can obtain two licenses to bind two computers.




------------------ 原始邮件 ------------------
发件人: "BjoernBo"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 下午3:13
收件人: "ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com>; 
抄送: "Gushijie"<1786570525@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ShanguUncle/UnityChatSDK] Trial time is up (#2)




Thank you very much! Do i need additional keys per development computer per computer the compiled app is running on?

**Comment by FluffySpectre** [comment]
Super, thanks for the info!

**Comment by FluffySpectre** [comment]
Hi,

the SDK is still not available in the AssetStore. I'll keep checking ;).
By the way: I integrated the SDK into my App and it works like a charm! Thank you for this awesome piece of software!

**Comment by ShanguUncle** [comment]
Thanks for your feedback. The previous version was rejected because&nbsp;the uploaded format does not meet the requirements and i re-uploaded it, the link will change. I will send you an email after passing. Please contact me if you have any questions.

---Original---

**Comment by ShanguUncle** [comment]
Hello, 
the sdk has not passed the review yet . 

https://assetstore.unity.com/packages/slug/154108

I added a PayPal payment . If you can use PayPal, I recommend you use PayPal to complete the order. 

Send your registration code to my email(1786570525@qq.com).
PayPal account:1786570525@qq.com 
https://www.paypal.me/ShanGuUncle

If you have any questions, please contact me anytime.Long-term update and support！

**Comment by ShanguUncle** [comment]
Hi，

I added a PayPal payment . If you can use PayPal, I recommend you use PayPal to complete the order.

Email:1786570525@qq.com.
PayPal account:1786570525@qq.com.

If you have any questions, please contact me anytime.Long-term update and support！





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BjoernBo"<notifications@github.com&gt;; 
发送时间: 2019年9月17日(星期二) 中午1:00
收件人: "ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com&gt;; 
抄送: "Gushijie"<1786570525@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ShanguUncle/UnityChatSDK] Trial time is up (#2)




Hi,
 
the SDK is still not available in the AssetStore. I'll keep checking ;).
 By the way: I integrated the SDK into my App and it works like a charm! Thank you for this awesome piece of software!

**Comment by FluffySpectre** [comment]
Hi, thank youvery much for the info! 
Since my company is buying things usually over the assetstore, i would like to wait for the release on the assetstore.

**Comment by FluffySpectre** [comment]
Still Error 404 on the AssetStore :-( 
Have you any updates on the status and takes the review by Unity usually that long? Have you any experience there?

**Comment by ShanguUncle** [comment]
![image](https://user-images.githubusercontent.com/42365977/66731183-9ee0b400-ee88-11e9-8c78-24e0319ccc11.png)
