### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by ilsanto17** [ShanguUncle/UnityChatSDK#3]
Hi I tried to register on https://item.taobao.com/item.htm?id=574700900943 but it doesn't let me register. Do you have a license to test this application? 60 seconds are few for me. How can we do? 
i am writing to you from Italy.

**Comment by ShanguUncle** [comment]
I have uploaded the sdk to asset store , it is under review，It should be OK&nbsp;in recent days.
This link will be valid after the platform is approved.
https://assetstore.unity.com/packages/slug/154108
PayPal link:
https://www.paypal.me/ShanGuUncle

**Comment by ilsanto17** [comment]
ok. Momentarily to carry out tests you can not give me any license?

**Comment by ShanguUncle** [comment]
If you need it&nbsp;eagerly, please send me your registration code,I&nbsp;will send you the license.you can buy it later on asset store.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ilsanto17"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月20日(星期五) 晚上11:18
收件人:&nbsp;"ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com&gt;;
抄送:&nbsp;"Gushijie"<1786570525@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ShanguUncle/UnityChatSDK] Licence (#3)




ok. Momentarily to carry out tests you can not give me any license?

**Comment by ilsanto17** [comment]
eU5+LhKcBFPYwmfzuG6alw==
thanks.

**Comment by ShanguUncle** [comment]
11267C818CC01BD0749AE6F7A7C335C8F2154F5D559E13A13EDA499F9CD0757C|tBzasFpfsSssgVPqqz/arA==


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ilsanto17"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月20日(星期五) 晚上11:49
收件人:&nbsp;"ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com&gt;;
抄送:&nbsp;"Gushijie"<1786570525@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ShanguUncle/UnityChatSDK] Licence (#3)




eU5+LhKcBFPYwmfzuG6alw==
 thanks.

**Comment by ilsanto17** [comment]
ok thank you soo much @ShanguUncle
