### ISSUE TITLE
Where I can buy licence other chinese language?

### ISSUE THREAD

**Issue by ilanb** [ShanguUncle/UnityChatSDK#5]
Hi,
Tried to buy on : [https://item.taobao.com/item.htm?spm=2013.1.20141001.2.6809e9d49oPong&id=600722678430&scm=1007.12144.95220.42296_0_0&pvid=5e797a34-b374-4e63-9f3e-92612e062969&utparam=%7B%22x_hestia_source%22%3A%2242296%22%2C%22x_object_type%22%3A%22item%22%2C%22x_mt%22%3A0%2C%22x_src%22%3A%2242296%22%2C%22x_pos%22%3A2%2C%22x_pvid%22%3A%225e797a34-b374-4e63-9f3e-92612e062969%22%2C%22x_object_id%22%3A600722678430%7D](url)

but I don't understand why add to cart not work etc... any chance to buy on other way ?

Thx

**Comment by ShanguUncle** [comment]
Hi,
The professional licence&nbsp; costs 254$ , send your registration code after payment (1786570525@qq.com).
You can pay with&nbsp; paypal or Taobao.
https://www.paypal.me/ShanGuUncle
https://item.taobao.com/item.htm?id=574700900943




---Original---

**Comment by ilanb** [comment]
Hi thanks,

Where I find the registration code ? is the number appear on unity editor ? 
And last question :-) does is support oculus quest device and hololens 2 (ARM) 

Thanks

**Comment by ShanguUncle** [comment]
Yes,I haven't tested it on HoloLens2 device yet, but it should be supported. You can test it and then register it.

**Comment by ilanb** [comment]
Hi, tried to pay via paypal but error message telling you accept payment only on your site...
