### ISSUE TITLE
Paypal error

### ISSUE THREAD

**Issue by ilanb** [ShanguUncle/UnityChatSDK#6]
I trying to pay via paypal like you said on email but I get message error you only accept paypal on your site.

Thanks,
https://screencast.com/t/1HXYVDlJfEM

**Comment by ShanguUncle** [comment]
Try to pay by&nbsp;using the paypal account
1786570525@qq.com


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ilanb"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月18日(星期五) 晚上7:33
收件人:&nbsp;"ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ShanguUncle/UnityChatSDK] Paypal error (#6)




I trying to pay via paypal like you said on email but I get message error you only accept paypal on your site.
 
Thanks,
 https://screencast.com/t/1HXYVDlJfEM

**Comment by ShanguUncle** [comment]
This problem has been solved.Try again.
