### ISSUE TITLE
Paypal same error 

### ISSUE THREAD

**Issue by ilanb** [ShanguUncle/UnityChatSDK#7]
Hey ShanguUncle, same error:
https://screencast.com/t/7vcn6qaDvBz

**Comment by ShanguUncle** [comment]
My paypal account address needs to be verified, please try again next week.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ilanb"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月18日(星期五) 晚上8:33
收件人:&nbsp;"ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ShanguUncle/UnityChatSDK] Paypal same error  (#7)




Hey ShanguUncle, same error:
 https://screencast.com/t/7vcn6qaDvBz

**Comment by ShanguUncle** [comment]
Send&nbsp;me&nbsp;your&nbsp;paypal&nbsp;account with your&nbsp;email ，dont on github.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ilanb"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月18日(星期五) 晚上8:33
收件人:&nbsp;"ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ShanguUncle/UnityChatSDK] Paypal same error  (#7)




Hey ShanguUncle, same error:
 https://screencast.com/t/7vcn6qaDvBz

**Comment by ShanguUncle** [comment]
This problem has been solved.Try again.
